/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author dell
 */
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public final class cart_orders extends javax.swing.JFrame {

    /**
     * Creates new form cart_orders
     */
  
  
  
public cart_orders() {
    initComponents();
    init();
}

public void init() {
    setFictionalBookImage();
    setScienceBookImage();
    setRomanticBookImage();
     setHistoryBookImage();
}

public void setFictionalBookImage() {
    URL url = getClass().getResource("/view/fictionalbookimage.jpg");
    if (url == null) {
        JOptionPane.showMessageDialog(this, "Fictional book image not found!");
        return;
    }
    ImageIcon icon = new ImageIcon(url);
    Image img = icon.getImage().getScaledInstance(fictionalbookimageLabel.getWidth(), fictionalbookimageLabel.getHeight(), Image.SCALE_SMOOTH);
    fictionalbookimageLabel.setIcon(new ImageIcon(img));
}

public void setScienceBookImage() {
    URL url = getClass().getResource("/view/sciencebookimage.jpg");  // Make sure this file exists
    if (url == null) {
        JOptionPane.showMessageDialog(this, "Science book image not found!");
        return;
    }
    ImageIcon icon = new ImageIcon(url);
    Image img = icon.getImage().getScaledInstance(sciencebookimageLabel.getWidth(), sciencebookimageLabel.getHeight(), Image.SCALE_SMOOTH);
    sciencebookimageLabel.setIcon(new ImageIcon(img));
}

public void setRomanticBookImage() {
    URL url = getClass().getResource("/view/romanticbookimage.jpg");  // Make sure this file exists
    if (url == null) {
        JOptionPane.showMessageDialog(this, "Romantic book image not found!");
        return;
    }
    ImageIcon icon = new ImageIcon(url);
    Image img = icon.getImage().getScaledInstance(romanticbookimageLabel.getWidth(), romanticbookimageLabel.getHeight(), Image.SCALE_SMOOTH);
    romanticbookimageLabel.setIcon(new ImageIcon(img));
}

public void setHistoryBookImage() {
    URL url = getClass().getResource("/view/historybookimage.jpg");  // Make sure this file exists
    if (url == null) {
        JOptionPane.showMessageDialog(this, "History book image not found!");
        return;
    }
    ImageIcon icon = new ImageIcon(url);
    Image img = icon.getImage().getScaledInstance(historybookimageLabel.getWidth(), historybookimageLabel.getHeight(), Image.SCALE_SMOOTH);
    historybookimageLabel.setIcon(new ImageIcon(img));
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mycartbutton = new javax.swing.JButton();
        myordersbutton = new javax.swing.JButton();
        book4ulabel = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        firstpanel = new javax.swing.JPanel();
        mycartlabel = new javax.swing.JLabel();
        proceedtocheckoutbutton = new javax.swing.JButton();
        applybutton = new javax.swing.JButton();
        subtotallabel = new javax.swing.JLabel();
        deliverylabel = new javax.swing.JLabel();
        discountlabel = new javax.swing.JLabel();
        totallabel = new javax.swing.JLabel();
        rs1 = new javax.swing.JLabel();
        rs2 = new javax.swing.JLabel();
        rs3 = new javax.swing.JLabel();
        rs4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        backarrowimagelabel = new javax.swing.JLabel();
        dustbiniconlabel = new javax.swing.JLabel();
        promocodeText = new javax.swing.JTextField();
        backgroundimageLabel = new javax.swing.JLabel();
        fictionalbookimageLabel = new javax.swing.JLabel();
        sciencebookimageLabel = new javax.swing.JLabel();
        romanticbookimageLabel = new javax.swing.JLabel();
        historybookimageLabel = new javax.swing.JLabel();
        secondpanel = new javax.swing.JPanel();
        myordersLabel = new javax.swing.JLabel();
        backarrowLabel = new javax.swing.JLabel();
        bgimageLabel = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        mycartbutton.setBackground(new java.awt.Color(255, 102, 0));
        mycartbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mycartbutton.setText("My Cart");
        mycartbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mycartbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(mycartbutton);
        mycartbutton.setBounds(16, 144, 157, 28);

        myordersbutton.setBackground(new java.awt.Color(255, 102, 0));
        myordersbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        myordersbutton.setText("My Orders");
        myordersbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myordersbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(myordersbutton);
        myordersbutton.setBounds(16, 209, 157, 28);

        book4ulabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        book4ulabel.setForeground(new java.awt.Color(255, 102, 0));
        book4ulabel.setText("Book4u");
        jPanel1.add(book4ulabel);
        book4ulabel.setBounds(20, 0, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 190, 630);

        Parent.setBackground(new java.awt.Color(255, 255, 204));
        Parent.setLayout(new java.awt.CardLayout());

        firstpanel.setBackground(new java.awt.Color(255, 255, 255));
        firstpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mycartlabel.setBackground(new java.awt.Color(0, 0, 0));
        mycartlabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mycartlabel.setText("My Cart");
        firstpanel.add(mycartlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 27, 142, 51));

        proceedtocheckoutbutton.setBackground(new java.awt.Color(255, 102, 0));
        proceedtocheckoutbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        proceedtocheckoutbutton.setText("Proceed to Checkout");
        firstpanel.add(proceedtocheckoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 571, 675, -1));

        applybutton.setBackground(new java.awt.Color(255, 102, 0));
        applybutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        applybutton.setText("Apply");
        firstpanel.add(applybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 327, 166, -1));

        subtotallabel.setBackground(new java.awt.Color(0, 0, 0));
        subtotallabel.setText("Subtotal");
        firstpanel.add(subtotallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 386, -1, -1));

        deliverylabel.setBackground(new java.awt.Color(0, 0, 0));
        deliverylabel.setText("Delivery Fee");
        firstpanel.add(deliverylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 420, -1, -1));

        discountlabel.setText("Discount");
        firstpanel.add(discountlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 454, -1, -1));

        totallabel.setText("Total");
        firstpanel.add(totallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 510, -1, -1));

        rs1.setText("Rs.");
        firstpanel.add(rs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 386, -1, -1));

        rs2.setText("Rs.");
        firstpanel.add(rs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 420, -1, -1));

        rs3.setText("Rs.");
        firstpanel.add(rs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 454, -1, -1));

        rs4.setText("Rs.");
        firstpanel.add(rs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 510, -1, -1));
        firstpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 364, 675, 10));
        firstpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 544, 675, 10));

        backarrowimagelabel.setForeground(new java.awt.Color(255, 255, 255));
        backarrowimagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/back arrow image.png"))); // NOI18N
        firstpanel.add(backarrowimagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 41, -1, 28));

        dustbiniconlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/dustbin_icon_image.png"))); // NOI18N
        dustbiniconlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dustbiniconlabelMouseClicked(evt);
            }
        });
        firstpanel.add(dustbiniconlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 27, -1, -1));

        promocodeText.setBackground(new java.awt.Color(204, 204, 204));
        promocodeText.setText("Have a promo code?");
        promocodeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                promocodeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                promocodeTextFocusLost(evt);
            }
        });
        firstpanel.add(promocodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 250, -1));

        backgroundimageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ChatGPT Image Jun 18, 2025, 10_40_10 AM.png"))); // NOI18N
        backgroundimageLabel.setText("jLabel1");
        firstpanel.add(backgroundimageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));
        firstpanel.add(fictionalbookimageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 40, 40));
        firstpanel.add(sciencebookimageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 40, 40));
        firstpanel.add(romanticbookimageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 40));
        firstpanel.add(historybookimageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 40, 40));

        Parent.add(firstpanel, "card2");

        secondpanel.setBackground(new java.awt.Color(204, 204, 204));
        secondpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myordersLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        myordersLabel.setText("My Orders");
        secondpanel.add(myordersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 49, -1, -1));

        backarrowLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/back arrow image.png"))); // NOI18N
        secondpanel.add(backarrowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 49, -1, -1));

        bgimageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ChatGPT Image Jun 18, 2025, 10_40_10 AM.png"))); // NOI18N
        bgimageLabel.setText("jLabel2");
        secondpanel.add(bgimageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));

        Parent.add(secondpanel, "card3");

        getContentPane().add(Parent);
        Parent.setBounds(190, 0, 720, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mycartbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycartbuttonActionPerformed
        // TODO add your handling code here:
        Parent.removeAll();
        Parent.add(firstpanel);
        Parent.repaint();
        Parent.revalidate();
        
    }//GEN-LAST:event_mycartbuttonActionPerformed

    private void myordersbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myordersbuttonActionPerformed
        // TODO add your handling code here:
         Parent.removeAll();
        Parent.add(secondpanel);
        Parent.repaint();
        Parent.revalidate();
    }//GEN-LAST:event_myordersbuttonActionPerformed

    private void promocodeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_promocodeTextFocusGained
        // TODO add your handling code here:
        if(promocodeText.getText().equals("Have a promo code?")){
        promocodeText.setText("");
}
    }//GEN-LAST:event_promocodeTextFocusGained

    private void promocodeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_promocodeTextFocusLost
        // TODO add your handling code here:
        if(promocodeText.getText().isEmpty()){
            promocodeText.setText("Have a promo code?");
}
    }//GEN-LAST:event_promocodeTextFocusLost

    
    private void dustbiniconlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dustbiniconlabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Dustbin icon clicked!");
    }//GEN-LAST:event_dustbiniconlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cart_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cart_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cart_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cart_orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cart_orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JButton applybutton;
    private javax.swing.JLabel backarrowLabel;
    private javax.swing.JLabel backarrowimagelabel;
    private javax.swing.JLabel backgroundimageLabel;
    private javax.swing.JLabel bgimageLabel;
    private javax.swing.JLabel book4ulabel;
    private javax.swing.JLabel deliverylabel;
    private javax.swing.JLabel discountlabel;
    private javax.swing.JLabel dustbiniconlabel;
    private javax.swing.JLabel fictionalbookimageLabel;
    private javax.swing.JPanel firstpanel;
    private javax.swing.JLabel historybookimageLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton mycartbutton;
    private javax.swing.JLabel mycartlabel;
    private javax.swing.JLabel myordersLabel;
    private javax.swing.JButton myordersbutton;
    private javax.swing.JButton proceedtocheckoutbutton;
    private javax.swing.JTextField promocodeText;
    private javax.swing.JLabel romanticbookimageLabel;
    private javax.swing.JLabel rs1;
    private javax.swing.JLabel rs2;
    private javax.swing.JLabel rs3;
    private javax.swing.JLabel rs4;
    private javax.swing.JLabel sciencebookimageLabel;
    private javax.swing.JPanel secondpanel;
    private javax.swing.JLabel subtotallabel;
    private javax.swing.JLabel totallabel;
    // End of variables declaration//GEN-END:variables
}
