/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author dell
 */
public class mycart extends javax.swing.JFrame {

    /**
     * Creates new form mycart
     */
    public mycart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book4uLabel = new javax.swing.JLabel();
        mycartLabel = new javax.swing.JLabel();
        backarrowLabel = new javax.swing.JLabel();
        dustbiniconLabel = new javax.swing.JLabel();
        proceedtocheckoutButton = new javax.swing.JButton();
        promocodeText = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        subtotalLabel = new javax.swing.JLabel();
        deliveryfeeLabel = new javax.swing.JLabel();
        discountLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book4uLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        book4uLabel.setForeground(new java.awt.Color(255, 102, 0));
        book4uLabel.setText("Book4u");
        getContentPane().add(book4uLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mycartLabel.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        mycartLabel.setText("My Cart");
        getContentPane().add(mycartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 37, -1, -1));

        backarrowLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/back arrow image.png"))); // NOI18N
        getContentPane().add(backarrowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 66, 29));

        dustbiniconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/dustbin_icon_image.png"))); // NOI18N
        dustbiniconLabel.setText("jLabel1");
        getContentPane().add(dustbiniconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 34, 47, 28));

        proceedtocheckoutButton.setBackground(new java.awt.Color(255, 102, 0));
        proceedtocheckoutButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        proceedtocheckoutButton.setText("Proceed to Checkout");
        proceedtocheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedtocheckoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(proceedtocheckoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 601, -1));

        promocodeText.setBackground(new java.awt.Color(204, 204, 204));
        promocodeText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        promocodeText.setText("Have a promo code?");
        getContentPane().add(promocodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 238, -1));

        applyButton.setBackground(new java.awt.Color(255, 102, 0));
        applyButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        applyButton.setText("Apply");
        getContentPane().add(applyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        subtotalLabel.setText("Subtotal");
        getContentPane().add(subtotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        deliveryfeeLabel.setText("Delivery Fee");
        getContentPane().add(deliveryfeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        discountLabel.setText("Discount");
        getContentPane().add(discountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel1.setText("Rs.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 70, -1));

        jLabel2.setText("Rs.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 70, 20));

        jLabel3.setText("Rs.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 346, 70, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 402, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Rs.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 650, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/mycartbackground image.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proceedtocheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedtocheckoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proceedtocheckoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mycart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mycart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mycart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mycart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mycart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel backarrowLabel;
    private javax.swing.JLabel book4uLabel;
    private javax.swing.JLabel deliveryfeeLabel;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JLabel dustbiniconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mycartLabel;
    private javax.swing.JButton proceedtocheckoutButton;
    private javax.swing.JTextField promocodeText;
    private javax.swing.JLabel subtotalLabel;
    // End of variables declaration//GEN-END:variables
}
