/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.event.ActionListener;

/**
 *
 * @author Nitro
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        book4ulogo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        Phonenumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phonenumberLabel = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        SignInBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        SignUpBtn2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPasswordField2.setText("jPasswordField2");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/6dea8d36-0f19-43dd-8b4e-2e9b2388524a.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/6dea8d36-0f19-43dd-8b4e-2e9b2388524a.jpg"))); // NOI18N

        book4ulogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/86e9c178dfec4dcd38c958a24734312006b04bf2.jpg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/6dea8d36-0f19-43dd-8b4e-2e9b2388524a.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/6dea8d36-0f19-43dd-8b4e-2e9b2388524a.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(102, 0, 0));
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 111, 136, -1));

        UsernameText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        UsernameText.setText("Enter your user name");
        UsernameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameTextFocusLost(evt);
            }
        });
        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 139, 221, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 293, 37, -1));

        emailLabel.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(102, 0, 0));
        emailLabel.setText("Email");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 168, 65, -1));

        Phonenumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Phonenumber.setText("Enter your phone number");
        Phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhonenumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhonenumberFocusLost(evt);
            }
        });
        Phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonenumberActionPerformed(evt);
            }
        });
        getContentPane().add(Phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 222, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 387, 144, -1));

        phonenumberLabel.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        phonenumberLabel.setForeground(new java.awt.Color(102, 0, 0));
        phonenumberLabel.setText("Phone number");
        getContentPane().add(phonenumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 287, 140, -1));

        EmailText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EmailText.setText("Enter your email");
        EmailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailTextFocusLost(evt);
            }
        });
        getContentPane().add(EmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 193, 222, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 228, 113, -1));

        Password.setText("jPasswordField1");
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 253, 222, -1));

        SignInBtn.setBackground(new java.awt.Color(255, 204, 204));
        SignInBtn.setText("Sign In");
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SignInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 35)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Book4U");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 50));

        SignUpBtn2.setBackground(new java.awt.Color(255, 204, 204));
        SignUpBtn2.setText("SignUp");
        SignUpBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Already have an account?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Screenshot 2025-06-06 162836.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 230, 520));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Screenshot 2025-06-06 151504.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 490, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void PhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonenumberActionPerformed

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInBtnActionPerformed

    private void SignUpBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtn2ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpBtn2ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void UsernameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTextFocusGained
        // TODO add your handling code here:
        if(UsernameText.getText().equals("Enter your user name")){
        UsernameText.setText("");
}
    }//GEN-LAST:event_UsernameTextFocusGained

    private void UsernameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameTextFocusLost
        // TODO add your handling code here:
        if(UsernameText.getText().isEmpty()){
            UsernameText.setText("Enter your user name");
}
    }//GEN-LAST:event_UsernameTextFocusLost

    private void EmailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailTextFocusGained
        // TODO add your handling code here:
        if(EmailText.getText().equals("Enter your email")){
        EmailText.setText("");
}
        
    }//GEN-LAST:event_EmailTextFocusGained

    private void EmailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailTextFocusLost
        // TODO add your handling code here:
        if(EmailText.getText().isEmpty()){
           EmailText.setText("Enter your email");
}
    }//GEN-LAST:event_EmailTextFocusLost

    private void PhonenumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhonenumberFocusGained
        // TODO add your handling code here:
        if(Phonenumber.getText().equals("Enter your phone number")){
        Phonenumber.setText("");
}
    }//GEN-LAST:event_PhonenumberFocusGained

    private void PhonenumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhonenumberFocusLost
        // TODO add your handling code here:
        if(Phonenumber.getText().isEmpty()){
           Phonenumber.setText("Enter your phone number");
}
    }//GEN-LAST:event_PhonenumberFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailText;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phonenumber;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JButton SignUpBtn2;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JLabel book4ulogo;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel phonenumberLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

public void addAddUserListener(ActionListener listener){
    SignUpBtn2.addActionListener(listener);
}

public void addLoginListener(ActionListener listener){
    SignInBtn.addActionListener(listener);
}
public javax.swing.JTextField getEmailField() {
        return EmailText; 
}
 public javax.swing.JPasswordField getPasswordField() {
        return Password;
    }
    public javax.swing.JTextField getUsernameField() {
        return UsernameText;
    }

    
    public javax.swing.JTextField getPhonenumber() {
        return Phonenumber;
    }
}










